import type { VocabularyLearningContent } from "@/features/vocabulary/types";
import { validateLearningContent } from "@/features/vocabulary/schemas/learning-content";
import { normalizeWord } from "@/features/vocabulary/services/normalize";
import type { VocabularyGenerationProvider } from "./types";
import { SEED_CONTENT } from "@/features/generation/seed-content";

function titleCase(word: string): string {
  return word
    .split(" ")
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join(" ");
}

function genericContent(word: string, normalized: string): VocabularyLearningContent {
  return {
    word: titleCase(word),
    normalizedWord: normalized,
    partOfSpeech: ["adjective"],
    pronunciation: {
      simple: normalized,
      confidence: "low",
    },
    definitions: [
      {
        text: `A GRE-relevant meaning of ${normalized} (mock definition for development).`,
        isPrimary: true,
      },
    ],
    etymology: {
      summary:
        "This word is not especially useful to decompose into modern GRE-style roots. Its historical origin would require dictionary verification beyond this mock provider.",
      isUsefulForRootLearning: false,
      uncertaintyNote: "Mock provider — not a factual etymology.",
      components: [],
    },
    memoryHook: {
      text: `Picture a sticky note labeled “${titleCase(word)}” taped to a GRE flashcard — a playful stand-in mnemonic for development.`,
      type: "visual",
    },
    synonyms: [{ word: "related", note: "placeholder" }, { word: "akin" }],
    antonyms: ["opposite"],
    exampleSentences: [
      {
        text: `The tutor used “${normalized}” in a sentence so the learner could infer the meaning from context.`,
      },
    ],
    wordFamily: [],
    usageNotes: "Generated by the mock provider for offline development.",
    confusedWith: [],
  };
}

export class MockVocabularyGenerationProvider
  implements VocabularyGenerationProvider
{
  readonly name = "mock";
  readonly model = "seed-mock-v1";

  async generate(word: string): Promise<VocabularyLearningContent> {
    const normalized = normalizeWord(word);
    if (!normalized.ok) {
      throw new Error(normalized.error);
    }

    const seed = SEED_CONTENT[normalized.normalized];
    const content = seed ?? genericContent(normalized.display, normalized.normalized);
    const parsed = validateLearningContent(content);
    if (!parsed.success) {
      throw new Error("Mock content failed validation");
    }
    return {
      ...parsed.data,
      pronunciation: {
        ipa: parsed.data.pronunciation.ipa ?? null,
        simple: parsed.data.pronunciation.simple ?? null,
        confidence: parsed.data.pronunciation.confidence ?? undefined,
      },
      definitions: parsed.data.definitions.map((d) => ({
        text: d.text,
        ...(d.sense ? { sense: d.sense } : {}),
        isPrimary: d.isPrimary,
      })),
      usageNotes: parsed.data.usageNotes ?? null,
      synonyms: parsed.data.synonyms.map((s) => ({
        word: s.word,
        note: s.note ?? null,
      })),
      exampleSentences: parsed.data.exampleSentences.map((e) => ({
        text: e.text,
        targetSense: e.targetSense ?? null,
      })),
      confusedWith: parsed.data.confusedWith.map((c) => ({
        word: c.word,
        distinction: c.distinction ?? null,
      })),
    };
  }
}
